controller_list:
  - name: fake_arm_group_controller
    joints:
      - p0_joint
      - p1_joint
      - p2_joint
      - p3_joint
      - p4_joint
initial:  # Define initial robot poses.
  - group: arm_group
    pose: lookup